# Generated by Django 6.0.3 on 2026-06-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
